---
# tasks file for httpd_core

- name: ensure default docroot directory exists
  file:
    path: "{{ httpd_default_docroot_dir }}"
    state: directory
    owner: "{{ httpd_user }}"
    group: "{{ httpd_default_docroot_group }}"
    mode: "{{ httpd_default_docroot_mode }}"
- name: Set default plaintext (non-ssl) vhost
  template:
    src: 10-default-plaintext.conf.{{ httpd_osver }}.j2
    dest: "{{ httpd_confd_dir }}/10-default-plaintext.conf"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_mode }}"
  when: httpd_allow_plaintext
- name: Set default ssl vhost
  template:
    src: 10-default-ssl.conf.{{ httpd_osver }}.j2
    dest: "{{ httpd_confd_dir }}/10-default-ssl.conf"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_mode }}"
  when: httpd_use_ssl