---
# tasks file for httpd_core
- name: Enforce core directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_dirmode }}"
  with_items:
    - "{{ httpd_serverroot }}"
    - "{{ httpd_conf_dir }}"
    - "{{ httpd_confd_dir }}"
    - "{{ httpd_vhost_dir }}"
    - "{{ httpd_moduleconf_dir }}"
    - "{{ httpd_log_dir }}"
    - "{{ httpd_custom_modules_dir }}"

- name: Symlink serverroot/run to {{ httpd_run_dir }}
  file:
    path: "{{ httpd_serverroot }}/run"
    state: link
    src: "{{ httpd_run_dir }}"
    force: yes
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_dirmode }}"

- name: Symlink serverroot/logs to {{ httpd_log_dir }}
  file:
    path: "{{ httpd_serverroot }}/logs"
    state: link
    src: "{{ httpd_log_dir }}"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_docroot_group }}"
    mode: "{{ httpd_docroot_mode }}"

- name: Symlink serverroot/modules to {{ httpd_module_dir }}
  file:
    path: "{{ httpd_serverroot }}/modules"
    state: link
    src: "{{ httpd_module_dir }}"
    force: yes
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    mode: "{{ httpd_dirmode }}"
