---
# tasks file for httpd_core
- name: Include OS-specific variables
  include_vars: "{{ httpd_osver }}.yml"

- name: Create needed directories and links
  import_tasks: directories.yml

- name: set core configuration files
  import_tasks: core_conffiles.yml

- name: set ssl settings
  import_tasks: ssl.yml
  when: httpd_use_ssl

- name: set default vhost(s) as needed
  import_tasks: default_vhost.yml
  when: httpd_default_vhost